# Generated by Django 4.2.2 on 2023-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdm',
            field=models.BooleanField(default=False, serialize=False),
            preserve_default=False,
        ),
    ]
