# Generated by Django 4.2.2 on 2023-06-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0006_rename_pdf_books_image_remove_books_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('edition', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('wikipedia', models.TextField()),
                ('image', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
