# Generated by Django 4.2.2 on 2023-06-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='username',
        ),
    ]
