# Generated by Django 4.2.2 on 2023-06-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_user_isadm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isAdm',
            field=models.BooleanField(default=False),
        ),
    ]
