# Generated by Django 4.2.2 on 2023-06-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0007_acceptedbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedbooks',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
